OGDF_BASE = /home/tilo/OGDF/OGDF
OGDF_INCLUDE_DIR         = $(OGDF_BASE)/include
OGDF_LIBRARY_DIR_DEBUG   = $(OGDF_BASE)/_debug
OGDF_LIBRARY_DIR_RELEASE = $(OGDF_BASE)/_release

DEBUG=1
# 0 = no debugging (release mode)
# 1 = debug mode
# 2 = GNU profiler (release mode)

